Fannyhenriques/project-design-handoff-vite

- src/data/links.json
- src/sections/testing.jsx
> removed testing.jsx

- src/re-components/Typography.jsx
- src/sections/Header/Introcontent.jsx
- src/sections/buttonsection/ButtonCard.jsx
added content in buttoncomponent and in introcomponent
> added content in buttoncomponent and in introcomponent

- public/icons/Vector.svg
- src/data/reviews.json
Add your Netlify link here.
PS. Don't forget to add it in your readme as well.
Add your collaborators here. Write their GitHub usernames in square brackets. If there's more than one, separate them with a comma, like this:
[github-username-1, github-username-2]
> finished reviews.json

- src/re-components/SectionTitle.jsx
added a sectiontitle with content in reusable components
> added a sectiontitle with content in reusable components

- index.html
- src/App.jsx
- src/re-components/Typography.jsx
> added content in app.jsx

- src/re-components/Typography.jsx
- src/styles/GlobalStyles.jsx
created a globalstyles component and moved the css from index.css there
> created a globalstyles component and moved the css from index.css there

- src/data/steps.json
- vite.config.js
installed babel and updated vite.config.js file
> installed babel and updated vite.config.js file

- src/App.jsx
- src/re-components/ReviewCard.jsx
- src/re-components/StepCard.jsx
- src/sections/socialproof/Socialproof.jsx
- vite.config.js
went back to the original code in vite.config.js due to error 500.
and connected the social proof tree to app.jsx
> went back to the original code in vite.config.js due to error 500

- src/App.jsx
- src/re-components/ReviewCard.jsx
- src/re-components/StepCard.jsx
- src/sections/main/Instructions.jsx
- src/sections/main/Steps.jsx
connected the instructions tree
> connected the instructions tree

- src/App.jsx
- src/styles/themes.js
cleaned up a little in app.jsx
> cleaned up a little in app.jsx

- src/re-components/Typography.jsx
- src/sections/Header/Introcontent.jsx
- src/styles/GlobalStyles.jsx
- src/styles/themes.js
> added content in introcontent

- src/data/steps.json
- src/sections/Header/Introcontent.jsx
- src/styles/GlobalStyles.jsx
- src/styles/themes.js
commented out code in themes.js
> commented out code in themes.js

- src/App.jsx
- src/re-components/ReviewCard.jsx
- src/sections/footer/Footer.jsx
- src/styles/themes.js
> added px into themes.js

- src/data/steps.json
- src/re-components/KindnessActCard.jsx
- src/re-components/SectionTitle.jsx
- src/re-components/StepCard.jsx
- src/re-components/Typography.jsx
- src/sections/Header/Slideshow.jsx
- src/sections/main/KindActInstructions.jsx
- src/sections/main/KindnessActSteps.jsx
- src/sections/main/Socialproof.jsx
changed pathways in jsonfile for icons, added content to stepcard and added the stepcard to the kindnessactsteps
> changed pathways in jsonfile for icons, added content to stepcard and added the stepcard to the kindnessactsteps

- src/data/reviews.json
- src/re-components/ReviewCard.jsx
- src/re-components/Typography.jsx
- src/sections/main/InstructionsSection.jsx
- src/sections/main/KindActInstructions.jsx
- src/sections/main/ReviewSection.jsx
- src/sections/main/Socialproof.jsx
- src/styles/GlobalStyles.jsx
added content in reviewcard, socialproof  and added a jsxfile to wrap the content
> added content in reviewcard, socialproof  and added a jsxfile to wrap the content

- src/sections/Header/slideshow.css
> styling for slideshow

- src/sections/Header/Slideshow.jsx
- src/sections/main/Socialproof.jsx
did som things in slideshow and socialproof
> did som things in slideshow and socialproof

- src/sections/Header/Slideshow.jsx
- src/sections/Header/slideshow.css
> tried again with the slider

- src/data/links.json
added more arrays in links.json
> added more arrays in links.json

- src/sections/footer/SocialLinks.jsx
buttond divided into divs, unfortunately stylinh still doesnt work
> buttond divided into divs, unfortunately stylinh still doesnt work

- src/re-components/Button2.jsx
- src/re-components/Button3.jsx
- src/sections/footer/SocialLinks.jsx
created more reusable button components to be ablte to style each one of them
> created more reusable button components

- src/re-components/Button.jsx
- src/re-components/Button2.jsx
- src/re-components/Typography.jsx
- src/sections/footer/Footer.jsx
- src/sections/footer/SocialLinks.jsx
added another FinePrint called FinePrintFooter with the correct colour, inside typography. also added an H3 in typography.  and did some styling on the buttons
> some styling

- src/data/links.json
- src/re-components/Button.jsx
- src/re-components/Button2.jsx
- src/re-components/Button3.jsx
- src/sections/footer/Footer.jsx
- src/sections/footer/SocialLinks.jsx
styling left for StartToday button
> styling done for button 2 and 3

- src/re-components/Button.jsx
- src/re-components/Button2.jsx
- src/sections/footer/SocialLinks.jsx
- src/sections/main/StartTodayButton1.jsx
FINISHED FOOTER STYLING FOR BUTTONS
> FINISHED FOOTER STYLING FOR BUTTONS

- src/sections/footer/Footer.jsx
cleaned up redundant code in footer
> cleaned up redundant code in footer

- src/re-components/Typography.jsx
- src/sections/footer/Footer.jsx
added styling for the fineprintfooter
> added styling for the fineprintfooter

- src/sections/footer/Footer.jsx
- src/sections/footer/SocialLinks.jsx
> tror jag fixade saker

- src/re-components/Typography.jsx
- src/sections/footer/SocialLinks.jsx
fixed some more styling issues
> fixed some more styling issues

- src/re-components/LogoAnimation.jsx
- src/re-components/ReviewCard.jsx
- src/sections/main/ReviewSection.jsx
- src/styles/themes.js
changed px to rem where it was possible
> changed px to rem where it was possible

- vite.config.js
> removed svrg from vite-config

- src/data/links.json
changed path to icons/svg in links.json
> changed path to icons/svg in links.json

- index.html
- src/re-components/StepCard.jsx
- src/sections/Header/Header.jsx
- src/sections/main/KindActInstructions.jsx
- src/sections/main/KindnessActSteps.jsx
Did some more styling for desktop.
> Gabysbranch

- index.html
- public/icons/star.svg
- src/re-components/ReviewCard.jsx
- src/re-components/Typography.jsx
- src/styles/GlobalStyles.jsx
- src/styles/themes.js
> test merge

- README.md
- src/re-components/Typography.jsx
- src/sections/footer/Footer.jsx
- src/styles/GlobalStyles.jsx
> cleaned up code

- src/re-components/ReviewCard.jsx
- src/sections/Header/Slideshow.jsx
added media for slideshow and put stars in a div in the reviewcard
> added media for slideshow and put stars in a div in the reviewcard

- src/re-components/LogoAnimation.jsx
- src/re-components/ReviewCard.jsx
- src/re-components/StepCard.jsx
- src/re-components/Typography.jsx
- src/sections/Header/Introcontent.jsx
- src/sections/footer/Footer.jsx
- src/sections/footer/LogoSection.jsx
- src/sections/footer/SocialLinks.jsx
- src/styles/GlobalStyles.jsx
updated styling and solved conflict in sociallinks
> updated styling and solved conflict in sociallinks
